%%%主函数，按顺序运行下列文件，即可得到全文所有结果，以mat文件保存
%step1:生成电动汽车数据
Sampling_EV
%step2:分析充电站的历史数据，评估可调度潜力
potential_history
%step3:由历史可调度潜力预测日前可调度潜力
potential_DA
%step4:计算日前无序充电负荷
disorder_charging
%step5:计算实时可调度潜力
potential_RT
%step6:由日前无序充电负荷参与日前电力市场投标
disorder_bidding
%step7:由联合报价模型确定节点边际电价，作为报价的参考（理论上应该由历史报价数据得到)，充电站联合报价模式
Bidding_price_reference
%step8:各充电站通过预测其他充电站的报价，独立报价，求解MPEC问题，调用函数bidding_DA_callback
bidding_DA
%step9:根据充电站的日前报价进行出清，其中考虑了线性规划的多解性，尽可能追踪日前计划
DA_clearing
%step10:个体竞标模式，实时，调用函数RT_single_Callback
RT_single
%step11:合作竞标模式，实时，调用函数RT_cooperation_Callback
RT_cooperation
%step12:集中调度模式，日前
DA_center
%step13:集中调度模式，实时，调用函数RT_center_Callback
RT_center
%step14:价格接受者，完全竞争市场，日前
DA_pricetaken
%step15:价格接受者，完全竞争市场，实时
RT_pricetaken